CC     := gcc
CFLAGS := -Wall -Wextra -Wfloat-equal -O2 -D_GNU_SOURCE

ifdef DEBUG
CFLAGS := -Wall -Wextra -Wfloat-equal -O0 -g -D_GNU_SOURCE
endif

BIN      := bin/supervisor
OBJS      = $(wildcard common/obj/*.o) $(wildcard supervisor/obj/*.o)

GAME_BIN  := bin/game
GAME_OBJS  = $(wildcard common/obj/*.o) $(wildcard game/obj/*.o)

TEST_BIN         := bin/test_orch_input
TEST_OBJS        := test/integration/supervisor/orchestrator/obj/test_input.o

TEST_CHUNKS_BIN  := bin/test_orch_input_chunks
TEST_CHUNKS_OBJS := test/integration/supervisor/orchestrator/obj/test_input_chunks.o

TEST_MATCHMAKING_BIN  := bin/test_matchmaking
TEST_MATCHMAKING_OBJS := test/integration/supervisor/matchmaker/obj/test_matchmaking.o

TEST_MATCHMAKING_QUEUE_BIN  := bin/test_matchmaking_queue
TEST_MATCHMAKING_QUEUE_OBJS := test/integration/supervisor/matchmaker/obj/test_matchmaking_queue.o

TEST_PORT_REAPER_BIN  := bin/test_port_reaper
TEST_PORT_REAPER_OBJS := test/unit/port_reaper/obj/test_port_reaper.o \
                         supervisor/obj/port_manager.o \
                         common/obj/hashmap.o \
                         common/obj/spsc_queue.o \
                         common/obj/log_system.o \
                         common/obj/util.o

TEST_GAME_BIN  := bin/test_game
TEST_GAME_OBJS := test/integration/game/obj/test_game.o

TEST_GAME_UNIT_BIN  := bin/test_game_unit
TEST_GAME_UNIT_OBJS := test/unit/game/obj/test_game_unit.o \
                       game/obj/game.o \
                       game/obj/player.o \
                       common/obj/hashmap.o \
                       common/obj/log_system.o \
                       common/obj/util.o

TEST_GAME_CREATE_BIN  := bin/test_game_create
TEST_GAME_CREATE_OBJS := test/unit/game_create/obj/test_game_create.o \
                         game/obj/game.o \
                         game/obj/player.o \
                         common/obj/hashmap.o \
                         common/obj/log_system.o \
                         common/obj/util.o

all: common supervisor game link link-game

common:
	$(MAKE) -C common

supervisor:
	$(MAKE) -C supervisor

game:
	$(MAKE) -C game

link:
	mkdir -p bin
	$(CC) $(CFLAGS) $(OBJS) -o $(BIN) -lpthread

link-game:
	mkdir -p bin
	$(CC) $(CFLAGS) $(GAME_OBJS) -o $(GAME_BIN) -lpthread

run: all
	./$(BIN)

test: all test-build link-test

test-build: test-build-orchestrator test-build-matchmaker test-build-port-reaper test-build-game

test-build-orchestrator:
	$(MAKE) -C test/integration/supervisor/orchestrator

test-build-matchmaker:
	$(MAKE) -C test/integration/supervisor/matchmaker

test-build-port-reaper:
	$(MAKE) -C test/unit/port_reaper

test-build-game:
	$(MAKE) -C test/integration/game

test-build-game-unit:
	$(MAKE) -C test/unit/game

test-build-game-create:
	$(MAKE) -C test/unit/game_create

link-test: link-test-orchestrator link-test-matchmaker link-test-port-reaper link-test-game

link-test-orchestrator: test-build-orchestrator
	mkdir -p bin
	$(CC) $(CFLAGS) $(TEST_OBJS) -o $(TEST_BIN)
	$(CC) $(CFLAGS) $(TEST_CHUNKS_OBJS) -o $(TEST_CHUNKS_BIN)

link-test-matchmaker: test-build-matchmaker
	mkdir -p bin
	$(CC) $(CFLAGS) $(TEST_MATCHMAKING_OBJS) -o $(TEST_MATCHMAKING_BIN)

link-test-matchmaking-queue: test-build-matchmaker
	mkdir -p bin
	$(CC) $(CFLAGS) $(TEST_MATCHMAKING_QUEUE_OBJS) -o $(TEST_MATCHMAKING_QUEUE_BIN)

link-test-port-reaper: test-build-port-reaper
	mkdir -p bin
	$(CC) $(CFLAGS) $(TEST_PORT_REAPER_OBJS) -o $(TEST_PORT_REAPER_BIN) -lpthread

link-test-game: test-build-game
	mkdir -p bin
	$(CC) $(CFLAGS) $(TEST_GAME_OBJS) -o $(TEST_GAME_BIN)

link-test-game-unit: test-build-game-unit
	mkdir -p bin
	$(CC) $(CFLAGS) $(TEST_GAME_UNIT_OBJS) -o $(TEST_GAME_UNIT_BIN)

link-test-game-create: test-build-game-create
	mkdir -p bin
	$(CC) $(CFLAGS) $(TEST_GAME_CREATE_OBJS) -o $(TEST_GAME_CREATE_BIN)

test-orchestrator: test
	@FIFO=$$(mktemp -u /tmp/sv_stdin_XXXXXX); \
	mkfifo $$FIFO; \
	./$(BIN) < $$FIFO & SPID=$$!; \
	exec 3>$$FIFO; \
	./$(TEST_BIN); R1=$$?; \
	./$(TEST_CHUNKS_BIN); R2=$$?; \
	echo exit >&3; \
	exec 3>&-; \
	wait $$SPID; \
	rm -f $$FIFO; \
	[ $$R1 -eq 0 ] && [ $$R2 -eq 0 ]

test-orchestrator-remote: link-test-orchestrator
	@./$(TEST_BIN); R1=$$?; \
	./$(TEST_CHUNKS_BIN); R2=$$?; \
	[ $$R1 -eq 0 ] && [ $$R2 -eq 0 ]

test-matchmaker: test
	@FIFO=$$(mktemp -u /tmp/sv_stdin_XXXXXX); \
	mkfifo $$FIFO; \
	./$(BIN) < $$FIFO & SPID=$$!; \
	exec 3>$$FIFO; \
	./$(TEST_MATCHMAKING_BIN); R1=$$?; \
	echo exit >&3; \
	exec 3>&-; \
	wait $$SPID; \
	rm -f $$FIFO; \
	[ $$R1 -eq 0 ]

test-matchmaker-remote: link-test-matchmaker
	@./$(TEST_MATCHMAKING_BIN)

test-matchmaking-queue-remote: link-test-matchmaking-queue
	@./$(TEST_MATCHMAKING_QUEUE_BIN)

test-unit: all test-build-port-reaper link-test-port-reaper test-build-game-unit link-test-game-unit test-build-game-create link-test-game-create
	@./$(TEST_PORT_REAPER_BIN)
	@./$(TEST_GAME_UNIT_BIN)
	@./$(TEST_GAME_CREATE_BIN)

test-port-reaper: all test-build-port-reaper link-test-port-reaper
	@./$(TEST_PORT_REAPER_BIN)

test-game-unit: all test-build-game-unit link-test-game-unit
	@./$(TEST_GAME_UNIT_BIN)

test-game-create: all test-build-game-create link-test-game-create
	@./$(TEST_GAME_CREATE_BIN)

test-game: all test-build-game link-test-game
	@./$(TEST_GAME_BIN)

clean:
	$(MAKE) -C common clean
	$(MAKE) -C supervisor clean
	$(MAKE) -C game clean
	$(MAKE) -C test/integration/supervisor/orchestrator clean
	$(MAKE) -C test/integration/supervisor/matchmaker clean
	$(MAKE) -C test/integration/game clean
	$(MAKE) -C test/unit/port_reaper clean
	$(MAKE) -C test/unit/game clean
	$(MAKE) -C test/unit/game_create clean
	rm -f $(TEST_PORT_REAPER_BIN)
	rm -f $(TEST_GAME_UNIT_BIN)
	rm -f $(TEST_GAME_CREATE_BIN)
	rm -rf bin

.PHONY: all common supervisor game link link-game run test \
        test-build test-build-orchestrator test-build-matchmaker test-build-port-reaper \
        link-test link-test-orchestrator link-test-matchmaker link-test-port-reaper \
        test-orchestrator test-orchestrator-remote \
        test-matchmaker test-matchmaker-remote \
        link-test-matchmaking-queue test-matchmaking-queue-remote \
        test-unit test-port-reaper test-game-unit \
        test-game test-build-game link-test-game \
        test-build-game-unit link-test-game-unit \
        test-game-create test-build-game-create link-test-game-create \
        clean
